name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Upload artifacts
        run: mkdir staging & cp build/libs/cass-class.jar staging-jar
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging-jar
  buildOnLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Build with Gradle
        run: ./gradlew nativeCompile
      - name: Upload artifacts
        run: mkdir staging & cp build/native/nativeCompile/cass-class staging-linux
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging-linux
  buildOnWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Create unistd.h
        run: cp include\unistd.h $env:VCToolsInstallDir\include
        shell: powershell
      - name: Build with Gradle
        run: ./gradlew nativeCompile
        shell: powershell
      - name: Upload artifacts
        run: mkdir staging; cp build/native/nativeCompile/cass-class.exe staging-windows
        shell: powershell
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging-windows
  createRelease:
    runs-on: ubuntu-latest
    needs:
      - buildOnLinux
      - buildOnWindows
      - buildJar
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: package
          path: staging-release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: staging-release/*
